export const ActionTypes = {
	FETCH_PRODUCTS:"FETCH_PRODUCTS",
	SET_PRODUCT_DETAIL:"SET_PRODUCT_DETAIL",
	RESET_PRODUCT_DETAIL:"RESET_PRODUCT_DETAIL",
	CART_STATUS:"CART_STATUS",
	ADD_ITEM_TO_CART:"ADD_ITEM_TO_CART",
}