export const ActionTypes = {
	FETCH_PRODUCTS:"FETCH_PRODUCTS",
	SET_PRODUCT_DETAIL:"SET_PRODUCT_DETAIL",
	RESET_PRODUCT_DETAIL:"RESET_PRODUCT_DETAIL",
	CART_STATUS:"CART_STATUS",
	ADD_ITEM_TO_CART:"ADD_ITEM_TO_CART",
	CART_REMOVE_ITEM:"CART_REMOVE_ITEM",
	INCREASE_ITEM:"INCREASE_ITEM",
	DECREASE_ITEM:"DECREASE_ITEM"
}


export const UserConstants = {
  USER_LIST_RESET:"USER_LIST_RESET:",
  USER_LOGIN_FAIL:"USER_LOGIN_FAIL:",
  USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST:",
  USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS:",
  USER_REGISTER_FAIL:"USER_REGISTER_FAIL:",
  USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST:",
  USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS:",
  USER_REGISTER_SUCCESS_RESET:"USER_REGISTER_SUCCESS_RESET:",
  USER_LOGOUT:"USER_LOGOUT:"
}